-- Reusable safe page templates per domain and optional campaign override
-- Run on PostgreSQL 14+

CREATE TABLE IF NOT EXISTS public.safe_pages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id integer NOT NULL REFERENCES public.domains(id) ON DELETE CASCADE,
    user_id integer REFERENCES public.users(id),
    name text NOT NULL,
    template text NOT NULL DEFAULT 'clean',
    content jsonb NOT NULL DEFAULT '{}'::jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    updated_by integer REFERENCES public.users(id)
);

ALTER TABLE public.campaigns
    ADD COLUMN IF NOT EXISTS safe_page_id integer REFERENCES public.safe_pages(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_safe_pages_domain_active
    ON public.safe_pages (domain_id, is_active);

CREATE INDEX IF NOT EXISTS idx_campaigns_safe_page_id
    ON public.campaigns (safe_page_id);

CREATE OR REPLACE FUNCTION public.fn_touch_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_safe_pages ON public.safe_pages;
CREATE TRIGGER trg_touch_safe_pages
BEFORE UPDATE ON public.safe_pages
FOR EACH ROW EXECUTE FUNCTION public.fn_touch_updated_at();
