-- Short link module
-- Run on PostgreSQL 14+

CREATE TABLE IF NOT EXISTS public.short_links (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id integer NOT NULL REFERENCES public.domains(id) ON DELETE CASCADE,
    user_id integer REFERENCES public.users(id),
    code text NOT NULL,
    title text,
    target_url text NOT NULL,
    is_active boolean DEFAULT true,
    clicks integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    updated_by integer REFERENCES public.users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_short_links_domain_code
    ON public.short_links (domain_id, lower(code));

CREATE INDEX IF NOT EXISTS idx_short_links_domain_active
    ON public.short_links (domain_id, is_active);

DROP TRIGGER IF EXISTS trg_touch_short_links ON public.short_links;
CREATE TRIGGER trg_touch_short_links
BEFORE UPDATE ON public.short_links
FOR EACH ROW EXECUTE FUNCTION public.fn_touch_updated_at();
