-- Cross-domain project organization.
-- Existing links remain unchanged and start without a project.

CREATE TABLE IF NOT EXISTS public.projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    name text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_by integer REFERENCES public.users(id),
    CONSTRAINT projects_name_not_blank CHECK (length(btrim(name)) BETWEEN 1 AND 150),
    CONSTRAINT projects_description_length CHECK (
        description IS NULL OR length(description) <= 500
    ),
    CONSTRAINT projects_status_check CHECK (status IN ('active', 'archived'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_owner_name
    ON public.projects (user_id, lower(name));

CREATE INDEX IF NOT EXISTS idx_projects_owner_status
    ON public.projects (user_id, status, id DESC);

ALTER TABLE public.campaigns
    ADD COLUMN IF NOT EXISTS project_id integer
    REFERENCES public.projects(id) ON DELETE SET NULL;

ALTER TABLE public.short_links
    ADD COLUMN IF NOT EXISTS project_id integer
    REFERENCES public.projects(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_campaigns_project
    ON public.campaigns (project_id, id DESC)
    WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_short_links_project
    ON public.short_links (project_id, id DESC)
    WHERE project_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_touch_projects ON public.projects;
CREATE TRIGGER trg_touch_projects
BEFORE UPDATE ON public.projects
FOR EACH ROW EXECUTE FUNCTION public.fn_touch_updated_at();

