-- Short link reporting support
-- Run on PostgreSQL 14+

-- Keep fresh installations deterministic even though this migration sorts
-- before 2026-06-09-short-links.sql by filename.
CREATE TABLE IF NOT EXISTS public.short_links (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id integer NOT NULL REFERENCES public.domains(id) ON DELETE CASCADE,
    user_id integer REFERENCES public.users(id),
    code text NOT NULL,
    title text,
    target_url text NOT NULL,
    is_active boolean DEFAULT true,
    clicks integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    updated_by integer REFERENCES public.users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_short_links_domain_code
    ON public.short_links (domain_id, lower(code));

ALTER TABLE public.traffic_logs
    ADD COLUMN IF NOT EXISTS short_link_id integer REFERENCES public.short_links(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_traffic_logs_short_link_date
    ON public.traffic_logs USING btree (short_link_id, created_at);

CREATE INDEX IF NOT EXISTS idx_traffic_logs_short_link_action
    ON public.traffic_logs USING btree (short_link_id, action);
